name: Actualizar Playlist Spotify
on:
  schedule:
    - cron: '0 11,18 * * 1-5' # lunes a viernes (Ajustado a UTC)
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Inyectar Caché de Spotify
        run: echo '${{ secrets.SPOTIPY_CACHE }}' > .cache

      - name: Correr script
        run: python main.py
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
